<a href="https://colab.research.google.com/github/Laxmi884/Data_Science_Python_Ass/blob/main/Copy_of_Assignment_NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [2]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [3]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [4]:
# Your code here

a= random_integers[0:5,2:4]
a.mean()


286058.5

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [5]:
# Create the 10 points
a = np.random.randint(5,20,(10,2))
a

array([[19, 12],
       [10, 16],
       [ 7, 12],
       [10, 19],
       [ 5,  9],
       [ 7,  7],
       [ 5, 14],
       [16,  6],
       [ 5,  8],
       [ 6,  8]])

In [6]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
def euclidean_distance(point1,point2):
  x1,y1 = point1
  x2,y2 = point2
  return round(((x2-x1)**2+(y2-y1)**2)**0.5,2)

ed = []
for i in range(10):
  il = []
  for j in range(10):
    il.append(euclidean_distance(a[i],a[j]))
  ed.append(np.asarray(il))
ed = np.asarray(ed)
print(ed)





[[ 0.    9.85 12.   11.4  14.32 13.   14.14  6.71 14.56 13.6 ]
 [ 9.85  0.    5.    3.    8.6   9.49  5.39 11.66  9.43  8.94]
 [12.    5.    0.    7.62  3.61  5.    2.83 10.82  4.47  4.12]
 [11.4   3.    7.62  0.   11.18 12.37  7.07 14.32 12.08 11.7 ]
 [14.32  8.6   3.61 11.18  0.    2.83  5.   11.4   1.    1.41]
 [13.    9.49  5.   12.37  2.83  0.    7.28  9.06  2.24  1.41]
 [14.14  5.39  2.83  7.07  5.    7.28  0.   13.6   6.    6.08]
 [ 6.71 11.66 10.82 14.32 11.4   9.06 13.6   0.   11.18 10.2 ]
 [14.56  9.43  4.47 12.08  1.    2.24  6.   11.18  0.    1.  ]
 [13.6   8.94  4.12 11.7   1.41  1.41  6.08 10.2   1.    0.  ]]


In [7]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.
def manhat(point1, point2):
  x1,y1 = point1
  x2,y2 = point2 
  return round(abs((x2-x1)+(y2-y1)))

mh = []
for i in range(10):
  il = []
  for j in range(10):
    il.append(manhat(a[i],a[j]))
  mh.append(np.asarray(il))
mh=np.asarray(mh)
print(mh)





[[ 0  5 12  2 17 17 12  9 18 17]
 [ 5  0  7  3 12 12  7  4 13 12]
 [12  7  0 10  5  5  0  3  6  5]
 [ 2  3 10  0 15 15 10  7 16 15]
 [17 12  5 15  0  0  5  8  1  0]
 [17 12  5 15  0  0  5  8  1  0]
 [12  7  0 10  5  5  0  3  6  5]
 [ 9  4  3  7  8  8  3  0  9  8]
 [18 13  6 16  1  1  6  9  0  1]
 [17 12  5 15  0  0  5  8  1  0]]


(10, 10)

## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [17]:
# Your code here
nearest_points_manhattan = []
for index,arr in enumerate(mh+np.identity(10)*1000):
  nearest_points_manhattan.append((a[index],a[arr.argmin()]))
print(nearest_points_manhattan)

nearest_points_ed = []
for index,arr in enumerate(ed+np.identity(10)*1000):
  nearest_points_ed.append((a[index],a[arr.argmin()]))
print(nearest_points_ed)


[(array([19, 12]), array([10, 19])), (array([10, 16]), array([10, 19])), (array([ 7, 12]), array([ 5, 14])), (array([10, 19]), array([19, 12])), (array([5, 9]), array([7, 7])), (array([7, 7]), array([5, 9])), (array([ 5, 14]), array([ 7, 12])), (array([16,  6]), array([ 7, 12])), (array([5, 8]), array([5, 9])), (array([6, 8]), array([5, 9]))]
[(array([19, 12]), array([16,  6])), (array([10, 16]), array([10, 19])), (array([ 7, 12]), array([ 5, 14])), (array([10, 19]), array([10, 16])), (array([5, 9]), array([5, 8])), (array([7, 7]), array([6, 8])), (array([ 5, 14]), array([ 7, 12])), (array([16,  6]), array([19, 12])), (array([5, 8]), array([5, 9])), (array([6, 8]), array([5, 8]))]


# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [24]:
from numpy.random.mtrand import rand
# Your code below ..
random_array = np.random.randint(1,100,size=(10,10))
print(random_array)
contiguous = []
for row in range(0,8):
  for col in range(0,8):
    contiguous.append(random_array[row:row+3,col:col+3])

ca = np.asarray(contiguous)
print(ca)









[[ 8 23 97 67 12 42 32  7 83 26]
 [12 52 90 51 51 14 59 64  6 23]
 [41 79 36 44 56  2 78 46 64 65]
 [27 41 86 54 19 81 56 99 81  5]
 [84 30 21 56 41 36 40 14 31 97]
 [19 38  7  3 84 51 32 47 35 93]
 [93 13 14 81 16 48 16 17 92 13]
 [41 34 40 62  7 14  3  9 24 87]
 [98 51 74 84 97  1 62 43 69 13]
 [73 15 46 58 85 84 53 21 33 83]]
[[[ 8 23 97]
  [12 52 90]
  [41 79 36]]

 [[23 97 67]
  [52 90 51]
  [79 36 44]]

 [[97 67 12]
  [90 51 51]
  [36 44 56]]

 [[67 12 42]
  [51 51 14]
  [44 56  2]]

 [[12 42 32]
  [51 14 59]
  [56  2 78]]

 [[42 32  7]
  [14 59 64]
  [ 2 78 46]]

 [[32  7 83]
  [59 64  6]
  [78 46 64]]

 [[ 7 83 26]
  [64  6 23]
  [46 64 65]]

 [[12 52 90]
  [41 79 36]
  [27 41 86]]

 [[52 90 51]
  [79 36 44]
  [41 86 54]]

 [[90 51 51]
  [36 44 56]
  [86 54 19]]

 [[51 51 14]
  [44 56  2]
  [54 19 81]]

 [[51 14 59]
  [56  2 78]
  [19 81 56]]

 [[14 59 64]
  [ 2 78 46]
  [81 56 99]]

 [[59 64  6]
  [78 46 64]
  [56 99 81]]

 [[64  6 23]
  [46 64 65]
  [99 81  5]]

 [[41 79 36]


#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [ ]:
# Your function below



